apiVersion: apps/v1
kind: Deployment
metadata:
    name: simptekapi-api-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: web
    template:
        metadata:
            labels:
                component: web
        spec:
            containers:
                - name: simptekapi-api
                  image: nayan2/simptekapi
                  ports:
                      - containerPort: 5000
